title: "Kindle to Notion"
description: "Export your Kindle highlights to Notion"
url: "https://tuliosousapro.github.io/Kindle-To-Notion-Extension"
baseurl: "/Kindle-To-Notion-Extension"
theme: jekyll-theme-minimal
